version: 2.1

defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:stretch


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          git clone https://github.com/openai/jukebox.git
          rm -rf ./jukebox/apex/
          cd jukebox/
          git clone https://github.com/nvidia/apex.git
      - run:
          no_output_timeout: 60m
          command: docker build -t btrude/jukebox-docker:latest -f Dockerfile .
      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push btrude/jukebox-docker:latest

  build_wip:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          git clone https://github.com/openai/jukebox.git
          rm -rf ./jukebox/apex/
          cd jukebox/
          git clone https://github.com/nvidia/apex.git
      - run:
          no_output_timeout: 60m
          command: docker build -t btrude/jukebox-docker:latest-$CIRCLE_SHA1 -f Dockerfile .
      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push btrude/jukebox-docker:latest-$CIRCLE_SHA1


workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - build_wip:
          filters:
            branches:
              ignore: master
